mrz_sw_auto:
  db:
    sql:
      hostname: 172.20.0.13:3306
      username: mrz_swauto
      password: CFU2wV8MRGPJ816c
      db_name: mrz_switch_automation
  security:
    salt: 0d25ad0a9885624feeff524008607b24