netcoco:
  db:
    sql:
      hostname: <db-hostname>:<db-port>
      username: <db-username>
      password: <db-password>
      db_name: <db-name>
  security:
    salt: <salt-in-hex-32digit>