apiVersion: v1
kind: Namespace
metadata:
  name: netcoco-io
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: netcoco
  name: netcoco
  namespace: netcoco-io

spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: netcoco
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcoco
  labels:
    app: netcoco
  namespace: netcoco-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netcoco
  template:
    metadata:
      labels:
        app: netcoco
    spec:
      containers:
      - name: netcoco
        image: quay.io/netcoco-io/netcoco
        imagePullPolicy: Always
        env:
          - name: COCO_PORT
            value: "" #(Default: port 8080)
          - name: COCO_DB_HOSTNAME
            value: "" #(localhost:3306)
          - name: COCO_DB_USERNAME
            value: ""
          - name: COCO_DB_PASSWORD
            value: ""
          - name: COCO_DB_NAME
            value: ""
          - name: COCO_SEC_SALT
            value: "" #(salt-in-hex-32digit)
        ports:
          - containerPort: 8080