// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mrzack99s/netcoco/ent/deletedvlanlog"
	"github.com/mrzack99s/netcoco/ent/device"
	"github.com/mrzack99s/netcoco/ent/predicate"
)

// DeletedVlanLogQuery is the builder for querying DeletedVlanLog entities.
type DeletedVlanLogQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.DeletedVlanLog
	// eager-loading edges.
	withOnDevice *DeviceQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeletedVlanLogQuery builder.
func (dvlq *DeletedVlanLogQuery) Where(ps ...predicate.DeletedVlanLog) *DeletedVlanLogQuery {
	dvlq.predicates = append(dvlq.predicates, ps...)
	return dvlq
}

// Limit adds a limit step to the query.
func (dvlq *DeletedVlanLogQuery) Limit(limit int) *DeletedVlanLogQuery {
	dvlq.limit = &limit
	return dvlq
}

// Offset adds an offset step to the query.
func (dvlq *DeletedVlanLogQuery) Offset(offset int) *DeletedVlanLogQuery {
	dvlq.offset = &offset
	return dvlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dvlq *DeletedVlanLogQuery) Unique(unique bool) *DeletedVlanLogQuery {
	dvlq.unique = &unique
	return dvlq
}

// Order adds an order step to the query.
func (dvlq *DeletedVlanLogQuery) Order(o ...OrderFunc) *DeletedVlanLogQuery {
	dvlq.order = append(dvlq.order, o...)
	return dvlq
}

// QueryOnDevice chains the current query on the "on_device" edge.
func (dvlq *DeletedVlanLogQuery) QueryOnDevice() *DeviceQuery {
	query := &DeviceQuery{config: dvlq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dvlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dvlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deletedvlanlog.Table, deletedvlanlog.FieldID, selector),
			sqlgraph.To(device.Table, device.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deletedvlanlog.OnDeviceTable, deletedvlanlog.OnDeviceColumn),
		)
		fromU = sqlgraph.SetNeighbors(dvlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DeletedVlanLog entity from the query.
// Returns a *NotFoundError when no DeletedVlanLog was found.
func (dvlq *DeletedVlanLogQuery) First(ctx context.Context) (*DeletedVlanLog, error) {
	nodes, err := dvlq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deletedvlanlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dvlq *DeletedVlanLogQuery) FirstX(ctx context.Context) *DeletedVlanLog {
	node, err := dvlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeletedVlanLog ID from the query.
// Returns a *NotFoundError when no DeletedVlanLog ID was found.
func (dvlq *DeletedVlanLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dvlq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deletedvlanlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dvlq *DeletedVlanLogQuery) FirstIDX(ctx context.Context) int {
	id, err := dvlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeletedVlanLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one DeletedVlanLog entity is not found.
// Returns a *NotFoundError when no DeletedVlanLog entities are found.
func (dvlq *DeletedVlanLogQuery) Only(ctx context.Context) (*DeletedVlanLog, error) {
	nodes, err := dvlq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deletedvlanlog.Label}
	default:
		return nil, &NotSingularError{deletedvlanlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dvlq *DeletedVlanLogQuery) OnlyX(ctx context.Context) *DeletedVlanLog {
	node, err := dvlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeletedVlanLog ID in the query.
// Returns a *NotSingularError when exactly one DeletedVlanLog ID is not found.
// Returns a *NotFoundError when no entities are found.
func (dvlq *DeletedVlanLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dvlq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deletedvlanlog.Label}
	default:
		err = &NotSingularError{deletedvlanlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dvlq *DeletedVlanLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := dvlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeletedVlanLogs.
func (dvlq *DeletedVlanLogQuery) All(ctx context.Context) ([]*DeletedVlanLog, error) {
	if err := dvlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return dvlq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (dvlq *DeletedVlanLogQuery) AllX(ctx context.Context) []*DeletedVlanLog {
	nodes, err := dvlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeletedVlanLog IDs.
func (dvlq *DeletedVlanLogQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := dvlq.Select(deletedvlanlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dvlq *DeletedVlanLogQuery) IDsX(ctx context.Context) []int {
	ids, err := dvlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dvlq *DeletedVlanLogQuery) Count(ctx context.Context) (int, error) {
	if err := dvlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return dvlq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (dvlq *DeletedVlanLogQuery) CountX(ctx context.Context) int {
	count, err := dvlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dvlq *DeletedVlanLogQuery) Exist(ctx context.Context) (bool, error) {
	if err := dvlq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return dvlq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (dvlq *DeletedVlanLogQuery) ExistX(ctx context.Context) bool {
	exist, err := dvlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeletedVlanLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dvlq *DeletedVlanLogQuery) Clone() *DeletedVlanLogQuery {
	if dvlq == nil {
		return nil
	}
	return &DeletedVlanLogQuery{
		config:       dvlq.config,
		limit:        dvlq.limit,
		offset:       dvlq.offset,
		order:        append([]OrderFunc{}, dvlq.order...),
		predicates:   append([]predicate.DeletedVlanLog{}, dvlq.predicates...),
		withOnDevice: dvlq.withOnDevice.Clone(),
		// clone intermediate query.
		sql:  dvlq.sql.Clone(),
		path: dvlq.path,
	}
}

// WithOnDevice tells the query-builder to eager-load the nodes that are connected to
// the "on_device" edge. The optional arguments are used to configure the query builder of the edge.
func (dvlq *DeletedVlanLogQuery) WithOnDevice(opts ...func(*DeviceQuery)) *DeletedVlanLogQuery {
	query := &DeviceQuery{config: dvlq.config}
	for _, opt := range opts {
		opt(query)
	}
	dvlq.withOnDevice = query
	return dvlq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		VlanID int `json:"vlan_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeletedVlanLog.Query().
//		GroupBy(deletedvlanlog.FieldVlanID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (dvlq *DeletedVlanLogQuery) GroupBy(field string, fields ...string) *DeletedVlanLogGroupBy {
	group := &DeletedVlanLogGroupBy{config: dvlq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := dvlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return dvlq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		VlanID int `json:"vlan_id,omitempty"`
//	}
//
//	client.DeletedVlanLog.Query().
//		Select(deletedvlanlog.FieldVlanID).
//		Scan(ctx, &v)
//
func (dvlq *DeletedVlanLogQuery) Select(field string, fields ...string) *DeletedVlanLogSelect {
	dvlq.fields = append([]string{field}, fields...)
	return &DeletedVlanLogSelect{DeletedVlanLogQuery: dvlq}
}

func (dvlq *DeletedVlanLogQuery) prepareQuery(ctx context.Context) error {
	for _, f := range dvlq.fields {
		if !deletedvlanlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dvlq.path != nil {
		prev, err := dvlq.path(ctx)
		if err != nil {
			return err
		}
		dvlq.sql = prev
	}
	return nil
}

func (dvlq *DeletedVlanLogQuery) sqlAll(ctx context.Context) ([]*DeletedVlanLog, error) {
	var (
		nodes       = []*DeletedVlanLog{}
		withFKs     = dvlq.withFKs
		_spec       = dvlq.querySpec()
		loadedTypes = [1]bool{
			dvlq.withOnDevice != nil,
		}
	)
	if dvlq.withOnDevice != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, deletedvlanlog.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &DeletedVlanLog{config: dvlq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, dvlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := dvlq.withOnDevice; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*DeletedVlanLog)
		for i := range nodes {
			if nodes[i].device_deleted_vlans == nil {
				continue
			}
			fk := *nodes[i].device_deleted_vlans
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(device.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "device_deleted_vlans" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.OnDevice = n
			}
		}
	}

	return nodes, nil
}

func (dvlq *DeletedVlanLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dvlq.querySpec()
	return sqlgraph.CountNodes(ctx, dvlq.driver, _spec)
}

func (dvlq *DeletedVlanLogQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := dvlq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (dvlq *DeletedVlanLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   deletedvlanlog.Table,
			Columns: deletedvlanlog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: deletedvlanlog.FieldID,
			},
		},
		From:   dvlq.sql,
		Unique: true,
	}
	if unique := dvlq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := dvlq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deletedvlanlog.FieldID)
		for i := range fields {
			if fields[i] != deletedvlanlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dvlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dvlq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dvlq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dvlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dvlq *DeletedVlanLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dvlq.driver.Dialect())
	t1 := builder.Table(deletedvlanlog.Table)
	selector := builder.Select(t1.Columns(deletedvlanlog.Columns...)...).From(t1)
	if dvlq.sql != nil {
		selector = dvlq.sql
		selector.Select(selector.Columns(deletedvlanlog.Columns...)...)
	}
	for _, p := range dvlq.predicates {
		p(selector)
	}
	for _, p := range dvlq.order {
		p(selector)
	}
	if offset := dvlq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dvlq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeletedVlanLogGroupBy is the group-by builder for DeletedVlanLog entities.
type DeletedVlanLogGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dvlgb *DeletedVlanLogGroupBy) Aggregate(fns ...AggregateFunc) *DeletedVlanLogGroupBy {
	dvlgb.fns = append(dvlgb.fns, fns...)
	return dvlgb
}

// Scan applies the group-by query and scans the result into the given value.
func (dvlgb *DeletedVlanLogGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := dvlgb.path(ctx)
	if err != nil {
		return err
	}
	dvlgb.sql = query
	return dvlgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (dvlgb *DeletedVlanLogGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := dvlgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (dvlgb *DeletedVlanLogGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(dvlgb.fields) > 1 {
		return nil, errors.New("ent: DeletedVlanLogGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := dvlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (dvlgb *DeletedVlanLogGroupBy) StringsX(ctx context.Context) []string {
	v, err := dvlgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (dvlgb *DeletedVlanLogGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = dvlgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deletedvlanlog.Label}
	default:
		err = fmt.Errorf("ent: DeletedVlanLogGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (dvlgb *DeletedVlanLogGroupBy) StringX(ctx context.Context) string {
	v, err := dvlgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (dvlgb *DeletedVlanLogGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(dvlgb.fields) > 1 {
		return nil, errors.New("ent: DeletedVlanLogGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := dvlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (dvlgb *DeletedVlanLogGroupBy) IntsX(ctx context.Context) []int {
	v, err := dvlgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (dvlgb *DeletedVlanLogGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = dvlgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deletedvlanlog.Label}
	default:
		err = fmt.Errorf("ent: DeletedVlanLogGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (dvlgb *DeletedVlanLogGroupBy) IntX(ctx context.Context) int {
	v, err := dvlgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (dvlgb *DeletedVlanLogGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(dvlgb.fields) > 1 {
		return nil, errors.New("ent: DeletedVlanLogGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := dvlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (dvlgb *DeletedVlanLogGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := dvlgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (dvlgb *DeletedVlanLogGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = dvlgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deletedvlanlog.Label}
	default:
		err = fmt.Errorf("ent: DeletedVlanLogGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (dvlgb *DeletedVlanLogGroupBy) Float64X(ctx context.Context) float64 {
	v, err := dvlgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (dvlgb *DeletedVlanLogGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(dvlgb.fields) > 1 {
		return nil, errors.New("ent: DeletedVlanLogGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := dvlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (dvlgb *DeletedVlanLogGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := dvlgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (dvlgb *DeletedVlanLogGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = dvlgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deletedvlanlog.Label}
	default:
		err = fmt.Errorf("ent: DeletedVlanLogGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (dvlgb *DeletedVlanLogGroupBy) BoolX(ctx context.Context) bool {
	v, err := dvlgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dvlgb *DeletedVlanLogGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range dvlgb.fields {
		if !deletedvlanlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := dvlgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dvlgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (dvlgb *DeletedVlanLogGroupBy) sqlQuery() *sql.Selector {
	selector := dvlgb.sql
	columns := make([]string, 0, len(dvlgb.fields)+len(dvlgb.fns))
	columns = append(columns, dvlgb.fields...)
	for _, fn := range dvlgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(dvlgb.fields...)
}

// DeletedVlanLogSelect is the builder for selecting fields of DeletedVlanLog entities.
type DeletedVlanLogSelect struct {
	*DeletedVlanLogQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (dvls *DeletedVlanLogSelect) Scan(ctx context.Context, v interface{}) error {
	if err := dvls.prepareQuery(ctx); err != nil {
		return err
	}
	dvls.sql = dvls.DeletedVlanLogQuery.sqlQuery(ctx)
	return dvls.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (dvls *DeletedVlanLogSelect) ScanX(ctx context.Context, v interface{}) {
	if err := dvls.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (dvls *DeletedVlanLogSelect) Strings(ctx context.Context) ([]string, error) {
	if len(dvls.fields) > 1 {
		return nil, errors.New("ent: DeletedVlanLogSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := dvls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (dvls *DeletedVlanLogSelect) StringsX(ctx context.Context) []string {
	v, err := dvls.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (dvls *DeletedVlanLogSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = dvls.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deletedvlanlog.Label}
	default:
		err = fmt.Errorf("ent: DeletedVlanLogSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (dvls *DeletedVlanLogSelect) StringX(ctx context.Context) string {
	v, err := dvls.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (dvls *DeletedVlanLogSelect) Ints(ctx context.Context) ([]int, error) {
	if len(dvls.fields) > 1 {
		return nil, errors.New("ent: DeletedVlanLogSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := dvls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (dvls *DeletedVlanLogSelect) IntsX(ctx context.Context) []int {
	v, err := dvls.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (dvls *DeletedVlanLogSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = dvls.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deletedvlanlog.Label}
	default:
		err = fmt.Errorf("ent: DeletedVlanLogSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (dvls *DeletedVlanLogSelect) IntX(ctx context.Context) int {
	v, err := dvls.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (dvls *DeletedVlanLogSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(dvls.fields) > 1 {
		return nil, errors.New("ent: DeletedVlanLogSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := dvls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (dvls *DeletedVlanLogSelect) Float64sX(ctx context.Context) []float64 {
	v, err := dvls.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (dvls *DeletedVlanLogSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = dvls.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deletedvlanlog.Label}
	default:
		err = fmt.Errorf("ent: DeletedVlanLogSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (dvls *DeletedVlanLogSelect) Float64X(ctx context.Context) float64 {
	v, err := dvls.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (dvls *DeletedVlanLogSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(dvls.fields) > 1 {
		return nil, errors.New("ent: DeletedVlanLogSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := dvls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (dvls *DeletedVlanLogSelect) BoolsX(ctx context.Context) []bool {
	v, err := dvls.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (dvls *DeletedVlanLogSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = dvls.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deletedvlanlog.Label}
	default:
		err = fmt.Errorf("ent: DeletedVlanLogSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (dvls *DeletedVlanLogSelect) BoolX(ctx context.Context) bool {
	v, err := dvls.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dvls *DeletedVlanLogSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := dvls.sqlQuery().Query()
	if err := dvls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (dvls *DeletedVlanLogSelect) sqlQuery() sql.Querier {
	selector := dvls.sql
	selector.Select(selector.Columns(dvls.fields...)...)
	return selector
}
