// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mrzack99s/netcoco/ent/ipstaticroutingtable"
	"github.com/mrzack99s/netcoco/ent/predicate"
)

// IPStaticRoutingTableDelete is the builder for deleting a IPStaticRoutingTable entity.
type IPStaticRoutingTableDelete struct {
	config
	hooks    []Hook
	mutation *IPStaticRoutingTableMutation
}

// Where adds a new predicate to the IPStaticRoutingTableDelete builder.
func (isrtd *IPStaticRoutingTableDelete) Where(ps ...predicate.IPStaticRoutingTable) *IPStaticRoutingTableDelete {
	isrtd.mutation.predicates = append(isrtd.mutation.predicates, ps...)
	return isrtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (isrtd *IPStaticRoutingTableDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(isrtd.hooks) == 0 {
		affected, err = isrtd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*IPStaticRoutingTableMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			isrtd.mutation = mutation
			affected, err = isrtd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(isrtd.hooks) - 1; i >= 0; i-- {
			mut = isrtd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, isrtd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (isrtd *IPStaticRoutingTableDelete) ExecX(ctx context.Context) int {
	n, err := isrtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (isrtd *IPStaticRoutingTableDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: ipstaticroutingtable.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: ipstaticroutingtable.FieldID,
			},
		},
	}
	if ps := isrtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, isrtd.driver, _spec)
}

// IPStaticRoutingTableDeleteOne is the builder for deleting a single IPStaticRoutingTable entity.
type IPStaticRoutingTableDeleteOne struct {
	isrtd *IPStaticRoutingTableDelete
}

// Exec executes the deletion query.
func (isrtdo *IPStaticRoutingTableDeleteOne) Exec(ctx context.Context) error {
	n, err := isrtdo.isrtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ipstaticroutingtable.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (isrtdo *IPStaticRoutingTableDeleteOne) ExecX(ctx context.Context) {
	isrtdo.isrtd.ExecX(ctx)
}
