// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mrzack99s/netcoco/ent/netinterface"
	"github.com/mrzack99s/netcoco/ent/predicate"
)

// NetInterfaceDelete is the builder for deleting a NetInterface entity.
type NetInterfaceDelete struct {
	config
	hooks    []Hook
	mutation *NetInterfaceMutation
}

// Where adds a new predicate to the NetInterfaceDelete builder.
func (nid *NetInterfaceDelete) Where(ps ...predicate.NetInterface) *NetInterfaceDelete {
	nid.mutation.predicates = append(nid.mutation.predicates, ps...)
	return nid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (nid *NetInterfaceDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(nid.hooks) == 0 {
		affected, err = nid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NetInterfaceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nid.mutation = mutation
			affected, err = nid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(nid.hooks) - 1; i >= 0; i-- {
			mut = nid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (nid *NetInterfaceDelete) ExecX(ctx context.Context) int {
	n, err := nid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (nid *NetInterfaceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: netinterface.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: netinterface.FieldID,
			},
		},
	}
	if ps := nid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, nid.driver, _spec)
}

// NetInterfaceDeleteOne is the builder for deleting a single NetInterface entity.
type NetInterfaceDeleteOne struct {
	nid *NetInterfaceDelete
}

// Exec executes the deletion query.
func (nido *NetInterfaceDeleteOne) Exec(ctx context.Context) error {
	n, err := nido.nid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{netinterface.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (nido *NetInterfaceDeleteOne) ExecX(ctx context.Context) {
	nido.nid.ExecX(ctx)
}
