// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mrzack99s/netcoco/ent/device"
	"github.com/mrzack99s/netcoco/ent/netinterface"
	"github.com/mrzack99s/netcoco/ent/netinterfacemode"
	"github.com/mrzack99s/netcoco/ent/portchannelinterface"
	"github.com/mrzack99s/netcoco/ent/predicate"
	"github.com/mrzack99s/netcoco/ent/vlan"
)

// NetInterfaceUpdate is the builder for updating NetInterface entities.
type NetInterfaceUpdate struct {
	config
	hooks    []Hook
	mutation *NetInterfaceMutation
}

// Where adds a new predicate for the NetInterfaceUpdate builder.
func (niu *NetInterfaceUpdate) Where(ps ...predicate.NetInterface) *NetInterfaceUpdate {
	niu.mutation.predicates = append(niu.mutation.predicates, ps...)
	return niu
}

// SetInterfaceName sets the "interface_name" field.
func (niu *NetInterfaceUpdate) SetInterfaceName(s string) *NetInterfaceUpdate {
	niu.mutation.SetInterfaceName(s)
	return niu
}

// SetInterfaceShutdown sets the "interface_shutdown" field.
func (niu *NetInterfaceUpdate) SetInterfaceShutdown(b bool) *NetInterfaceUpdate {
	niu.mutation.SetInterfaceShutdown(b)
	return niu
}

// SetNillableInterfaceShutdown sets the "interface_shutdown" field if the given value is not nil.
func (niu *NetInterfaceUpdate) SetNillableInterfaceShutdown(b *bool) *NetInterfaceUpdate {
	if b != nil {
		niu.SetInterfaceShutdown(*b)
	}
	return niu
}

// SetOnDeviceID sets the "on_device" edge to the Device entity by ID.
func (niu *NetInterfaceUpdate) SetOnDeviceID(id int) *NetInterfaceUpdate {
	niu.mutation.SetOnDeviceID(id)
	return niu
}

// SetNillableOnDeviceID sets the "on_device" edge to the Device entity by ID if the given value is not nil.
func (niu *NetInterfaceUpdate) SetNillableOnDeviceID(id *int) *NetInterfaceUpdate {
	if id != nil {
		niu = niu.SetOnDeviceID(*id)
	}
	return niu
}

// SetOnDevice sets the "on_device" edge to the Device entity.
func (niu *NetInterfaceUpdate) SetOnDevice(d *Device) *NetInterfaceUpdate {
	return niu.SetOnDeviceID(d.ID)
}

// SetOnPoInterfaceID sets the "on_po_interface" edge to the PortChannelInterface entity by ID.
func (niu *NetInterfaceUpdate) SetOnPoInterfaceID(id int) *NetInterfaceUpdate {
	niu.mutation.SetOnPoInterfaceID(id)
	return niu
}

// SetNillableOnPoInterfaceID sets the "on_po_interface" edge to the PortChannelInterface entity by ID if the given value is not nil.
func (niu *NetInterfaceUpdate) SetNillableOnPoInterfaceID(id *int) *NetInterfaceUpdate {
	if id != nil {
		niu = niu.SetOnPoInterfaceID(*id)
	}
	return niu
}

// SetOnPoInterface sets the "on_po_interface" edge to the PortChannelInterface entity.
func (niu *NetInterfaceUpdate) SetOnPoInterface(p *PortChannelInterface) *NetInterfaceUpdate {
	return niu.SetOnPoInterfaceID(p.ID)
}

// SetModeID sets the "mode" edge to the NetInterfaceMode entity by ID.
func (niu *NetInterfaceUpdate) SetModeID(id int) *NetInterfaceUpdate {
	niu.mutation.SetModeID(id)
	return niu
}

// SetNillableModeID sets the "mode" edge to the NetInterfaceMode entity by ID if the given value is not nil.
func (niu *NetInterfaceUpdate) SetNillableModeID(id *int) *NetInterfaceUpdate {
	if id != nil {
		niu = niu.SetModeID(*id)
	}
	return niu
}

// SetMode sets the "mode" edge to the NetInterfaceMode entity.
func (niu *NetInterfaceUpdate) SetMode(n *NetInterfaceMode) *NetInterfaceUpdate {
	return niu.SetModeID(n.ID)
}

// AddHaveVlanIDs adds the "have_vlans" edge to the Vlan entity by IDs.
func (niu *NetInterfaceUpdate) AddHaveVlanIDs(ids ...int) *NetInterfaceUpdate {
	niu.mutation.AddHaveVlanIDs(ids...)
	return niu
}

// AddHaveVlans adds the "have_vlans" edges to the Vlan entity.
func (niu *NetInterfaceUpdate) AddHaveVlans(v ...*Vlan) *NetInterfaceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return niu.AddHaveVlanIDs(ids...)
}

// SetNativeOnVlanID sets the "native_on_vlan" edge to the Vlan entity by ID.
func (niu *NetInterfaceUpdate) SetNativeOnVlanID(id int) *NetInterfaceUpdate {
	niu.mutation.SetNativeOnVlanID(id)
	return niu
}

// SetNillableNativeOnVlanID sets the "native_on_vlan" edge to the Vlan entity by ID if the given value is not nil.
func (niu *NetInterfaceUpdate) SetNillableNativeOnVlanID(id *int) *NetInterfaceUpdate {
	if id != nil {
		niu = niu.SetNativeOnVlanID(*id)
	}
	return niu
}

// SetNativeOnVlan sets the "native_on_vlan" edge to the Vlan entity.
func (niu *NetInterfaceUpdate) SetNativeOnVlan(v *Vlan) *NetInterfaceUpdate {
	return niu.SetNativeOnVlanID(v.ID)
}

// Mutation returns the NetInterfaceMutation object of the builder.
func (niu *NetInterfaceUpdate) Mutation() *NetInterfaceMutation {
	return niu.mutation
}

// ClearOnDevice clears the "on_device" edge to the Device entity.
func (niu *NetInterfaceUpdate) ClearOnDevice() *NetInterfaceUpdate {
	niu.mutation.ClearOnDevice()
	return niu
}

// ClearOnPoInterface clears the "on_po_interface" edge to the PortChannelInterface entity.
func (niu *NetInterfaceUpdate) ClearOnPoInterface() *NetInterfaceUpdate {
	niu.mutation.ClearOnPoInterface()
	return niu
}

// ClearMode clears the "mode" edge to the NetInterfaceMode entity.
func (niu *NetInterfaceUpdate) ClearMode() *NetInterfaceUpdate {
	niu.mutation.ClearMode()
	return niu
}

// ClearHaveVlans clears all "have_vlans" edges to the Vlan entity.
func (niu *NetInterfaceUpdate) ClearHaveVlans() *NetInterfaceUpdate {
	niu.mutation.ClearHaveVlans()
	return niu
}

// RemoveHaveVlanIDs removes the "have_vlans" edge to Vlan entities by IDs.
func (niu *NetInterfaceUpdate) RemoveHaveVlanIDs(ids ...int) *NetInterfaceUpdate {
	niu.mutation.RemoveHaveVlanIDs(ids...)
	return niu
}

// RemoveHaveVlans removes "have_vlans" edges to Vlan entities.
func (niu *NetInterfaceUpdate) RemoveHaveVlans(v ...*Vlan) *NetInterfaceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return niu.RemoveHaveVlanIDs(ids...)
}

// ClearNativeOnVlan clears the "native_on_vlan" edge to the Vlan entity.
func (niu *NetInterfaceUpdate) ClearNativeOnVlan() *NetInterfaceUpdate {
	niu.mutation.ClearNativeOnVlan()
	return niu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (niu *NetInterfaceUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(niu.hooks) == 0 {
		if err = niu.check(); err != nil {
			return 0, err
		}
		affected, err = niu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NetInterfaceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = niu.check(); err != nil {
				return 0, err
			}
			niu.mutation = mutation
			affected, err = niu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(niu.hooks) - 1; i >= 0; i-- {
			mut = niu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, niu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (niu *NetInterfaceUpdate) SaveX(ctx context.Context) int {
	affected, err := niu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (niu *NetInterfaceUpdate) Exec(ctx context.Context) error {
	_, err := niu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (niu *NetInterfaceUpdate) ExecX(ctx context.Context) {
	if err := niu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (niu *NetInterfaceUpdate) check() error {
	if v, ok := niu.mutation.InterfaceName(); ok {
		if err := netinterface.InterfaceNameValidator(v); err != nil {
			return &ValidationError{Name: "interface_name", err: fmt.Errorf("ent: validator failed for field \"interface_name\": %w", err)}
		}
	}
	return nil
}

func (niu *NetInterfaceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   netinterface.Table,
			Columns: netinterface.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: netinterface.FieldID,
			},
		},
	}
	if ps := niu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := niu.mutation.InterfaceName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: netinterface.FieldInterfaceName,
		})
	}
	if value, ok := niu.mutation.InterfaceShutdown(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: netinterface.FieldInterfaceShutdown,
		})
	}
	if niu.mutation.OnDeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.OnDeviceTable,
			Columns: []string{netinterface.OnDeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: device.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := niu.mutation.OnDeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.OnDeviceTable,
			Columns: []string{netinterface.OnDeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: device.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if niu.mutation.OnPoInterfaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.OnPoInterfaceTable,
			Columns: []string{netinterface.OnPoInterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: portchannelinterface.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := niu.mutation.OnPoInterfaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.OnPoInterfaceTable,
			Columns: []string{netinterface.OnPoInterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: portchannelinterface.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if niu.mutation.ModeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.ModeTable,
			Columns: []string{netinterface.ModeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: netinterfacemode.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := niu.mutation.ModeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.ModeTable,
			Columns: []string{netinterface.ModeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: netinterfacemode.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if niu.mutation.HaveVlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   netinterface.HaveVlansTable,
			Columns: netinterface.HaveVlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vlan.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := niu.mutation.RemovedHaveVlansIDs(); len(nodes) > 0 && !niu.mutation.HaveVlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   netinterface.HaveVlansTable,
			Columns: netinterface.HaveVlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vlan.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := niu.mutation.HaveVlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   netinterface.HaveVlansTable,
			Columns: netinterface.HaveVlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vlan.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if niu.mutation.NativeOnVlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.NativeOnVlanTable,
			Columns: []string{netinterface.NativeOnVlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vlan.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := niu.mutation.NativeOnVlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.NativeOnVlanTable,
			Columns: []string{netinterface.NativeOnVlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vlan.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, niu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{netinterface.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// NetInterfaceUpdateOne is the builder for updating a single NetInterface entity.
type NetInterfaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NetInterfaceMutation
}

// SetInterfaceName sets the "interface_name" field.
func (niuo *NetInterfaceUpdateOne) SetInterfaceName(s string) *NetInterfaceUpdateOne {
	niuo.mutation.SetInterfaceName(s)
	return niuo
}

// SetInterfaceShutdown sets the "interface_shutdown" field.
func (niuo *NetInterfaceUpdateOne) SetInterfaceShutdown(b bool) *NetInterfaceUpdateOne {
	niuo.mutation.SetInterfaceShutdown(b)
	return niuo
}

// SetNillableInterfaceShutdown sets the "interface_shutdown" field if the given value is not nil.
func (niuo *NetInterfaceUpdateOne) SetNillableInterfaceShutdown(b *bool) *NetInterfaceUpdateOne {
	if b != nil {
		niuo.SetInterfaceShutdown(*b)
	}
	return niuo
}

// SetOnDeviceID sets the "on_device" edge to the Device entity by ID.
func (niuo *NetInterfaceUpdateOne) SetOnDeviceID(id int) *NetInterfaceUpdateOne {
	niuo.mutation.SetOnDeviceID(id)
	return niuo
}

// SetNillableOnDeviceID sets the "on_device" edge to the Device entity by ID if the given value is not nil.
func (niuo *NetInterfaceUpdateOne) SetNillableOnDeviceID(id *int) *NetInterfaceUpdateOne {
	if id != nil {
		niuo = niuo.SetOnDeviceID(*id)
	}
	return niuo
}

// SetOnDevice sets the "on_device" edge to the Device entity.
func (niuo *NetInterfaceUpdateOne) SetOnDevice(d *Device) *NetInterfaceUpdateOne {
	return niuo.SetOnDeviceID(d.ID)
}

// SetOnPoInterfaceID sets the "on_po_interface" edge to the PortChannelInterface entity by ID.
func (niuo *NetInterfaceUpdateOne) SetOnPoInterfaceID(id int) *NetInterfaceUpdateOne {
	niuo.mutation.SetOnPoInterfaceID(id)
	return niuo
}

// SetNillableOnPoInterfaceID sets the "on_po_interface" edge to the PortChannelInterface entity by ID if the given value is not nil.
func (niuo *NetInterfaceUpdateOne) SetNillableOnPoInterfaceID(id *int) *NetInterfaceUpdateOne {
	if id != nil {
		niuo = niuo.SetOnPoInterfaceID(*id)
	}
	return niuo
}

// SetOnPoInterface sets the "on_po_interface" edge to the PortChannelInterface entity.
func (niuo *NetInterfaceUpdateOne) SetOnPoInterface(p *PortChannelInterface) *NetInterfaceUpdateOne {
	return niuo.SetOnPoInterfaceID(p.ID)
}

// SetModeID sets the "mode" edge to the NetInterfaceMode entity by ID.
func (niuo *NetInterfaceUpdateOne) SetModeID(id int) *NetInterfaceUpdateOne {
	niuo.mutation.SetModeID(id)
	return niuo
}

// SetNillableModeID sets the "mode" edge to the NetInterfaceMode entity by ID if the given value is not nil.
func (niuo *NetInterfaceUpdateOne) SetNillableModeID(id *int) *NetInterfaceUpdateOne {
	if id != nil {
		niuo = niuo.SetModeID(*id)
	}
	return niuo
}

// SetMode sets the "mode" edge to the NetInterfaceMode entity.
func (niuo *NetInterfaceUpdateOne) SetMode(n *NetInterfaceMode) *NetInterfaceUpdateOne {
	return niuo.SetModeID(n.ID)
}

// AddHaveVlanIDs adds the "have_vlans" edge to the Vlan entity by IDs.
func (niuo *NetInterfaceUpdateOne) AddHaveVlanIDs(ids ...int) *NetInterfaceUpdateOne {
	niuo.mutation.AddHaveVlanIDs(ids...)
	return niuo
}

// AddHaveVlans adds the "have_vlans" edges to the Vlan entity.
func (niuo *NetInterfaceUpdateOne) AddHaveVlans(v ...*Vlan) *NetInterfaceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return niuo.AddHaveVlanIDs(ids...)
}

// SetNativeOnVlanID sets the "native_on_vlan" edge to the Vlan entity by ID.
func (niuo *NetInterfaceUpdateOne) SetNativeOnVlanID(id int) *NetInterfaceUpdateOne {
	niuo.mutation.SetNativeOnVlanID(id)
	return niuo
}

// SetNillableNativeOnVlanID sets the "native_on_vlan" edge to the Vlan entity by ID if the given value is not nil.
func (niuo *NetInterfaceUpdateOne) SetNillableNativeOnVlanID(id *int) *NetInterfaceUpdateOne {
	if id != nil {
		niuo = niuo.SetNativeOnVlanID(*id)
	}
	return niuo
}

// SetNativeOnVlan sets the "native_on_vlan" edge to the Vlan entity.
func (niuo *NetInterfaceUpdateOne) SetNativeOnVlan(v *Vlan) *NetInterfaceUpdateOne {
	return niuo.SetNativeOnVlanID(v.ID)
}

// Mutation returns the NetInterfaceMutation object of the builder.
func (niuo *NetInterfaceUpdateOne) Mutation() *NetInterfaceMutation {
	return niuo.mutation
}

// ClearOnDevice clears the "on_device" edge to the Device entity.
func (niuo *NetInterfaceUpdateOne) ClearOnDevice() *NetInterfaceUpdateOne {
	niuo.mutation.ClearOnDevice()
	return niuo
}

// ClearOnPoInterface clears the "on_po_interface" edge to the PortChannelInterface entity.
func (niuo *NetInterfaceUpdateOne) ClearOnPoInterface() *NetInterfaceUpdateOne {
	niuo.mutation.ClearOnPoInterface()
	return niuo
}

// ClearMode clears the "mode" edge to the NetInterfaceMode entity.
func (niuo *NetInterfaceUpdateOne) ClearMode() *NetInterfaceUpdateOne {
	niuo.mutation.ClearMode()
	return niuo
}

// ClearHaveVlans clears all "have_vlans" edges to the Vlan entity.
func (niuo *NetInterfaceUpdateOne) ClearHaveVlans() *NetInterfaceUpdateOne {
	niuo.mutation.ClearHaveVlans()
	return niuo
}

// RemoveHaveVlanIDs removes the "have_vlans" edge to Vlan entities by IDs.
func (niuo *NetInterfaceUpdateOne) RemoveHaveVlanIDs(ids ...int) *NetInterfaceUpdateOne {
	niuo.mutation.RemoveHaveVlanIDs(ids...)
	return niuo
}

// RemoveHaveVlans removes "have_vlans" edges to Vlan entities.
func (niuo *NetInterfaceUpdateOne) RemoveHaveVlans(v ...*Vlan) *NetInterfaceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return niuo.RemoveHaveVlanIDs(ids...)
}

// ClearNativeOnVlan clears the "native_on_vlan" edge to the Vlan entity.
func (niuo *NetInterfaceUpdateOne) ClearNativeOnVlan() *NetInterfaceUpdateOne {
	niuo.mutation.ClearNativeOnVlan()
	return niuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (niuo *NetInterfaceUpdateOne) Select(field string, fields ...string) *NetInterfaceUpdateOne {
	niuo.fields = append([]string{field}, fields...)
	return niuo
}

// Save executes the query and returns the updated NetInterface entity.
func (niuo *NetInterfaceUpdateOne) Save(ctx context.Context) (*NetInterface, error) {
	var (
		err  error
		node *NetInterface
	)
	if len(niuo.hooks) == 0 {
		if err = niuo.check(); err != nil {
			return nil, err
		}
		node, err = niuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NetInterfaceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = niuo.check(); err != nil {
				return nil, err
			}
			niuo.mutation = mutation
			node, err = niuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(niuo.hooks) - 1; i >= 0; i-- {
			mut = niuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, niuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (niuo *NetInterfaceUpdateOne) SaveX(ctx context.Context) *NetInterface {
	node, err := niuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (niuo *NetInterfaceUpdateOne) Exec(ctx context.Context) error {
	_, err := niuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (niuo *NetInterfaceUpdateOne) ExecX(ctx context.Context) {
	if err := niuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (niuo *NetInterfaceUpdateOne) check() error {
	if v, ok := niuo.mutation.InterfaceName(); ok {
		if err := netinterface.InterfaceNameValidator(v); err != nil {
			return &ValidationError{Name: "interface_name", err: fmt.Errorf("ent: validator failed for field \"interface_name\": %w", err)}
		}
	}
	return nil
}

func (niuo *NetInterfaceUpdateOne) sqlSave(ctx context.Context) (_node *NetInterface, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   netinterface.Table,
			Columns: netinterface.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: netinterface.FieldID,
			},
		},
	}
	id, ok := niuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing NetInterface.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := niuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, netinterface.FieldID)
		for _, f := range fields {
			if !netinterface.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != netinterface.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := niuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := niuo.mutation.InterfaceName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: netinterface.FieldInterfaceName,
		})
	}
	if value, ok := niuo.mutation.InterfaceShutdown(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: netinterface.FieldInterfaceShutdown,
		})
	}
	if niuo.mutation.OnDeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.OnDeviceTable,
			Columns: []string{netinterface.OnDeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: device.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := niuo.mutation.OnDeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.OnDeviceTable,
			Columns: []string{netinterface.OnDeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: device.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if niuo.mutation.OnPoInterfaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.OnPoInterfaceTable,
			Columns: []string{netinterface.OnPoInterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: portchannelinterface.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := niuo.mutation.OnPoInterfaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.OnPoInterfaceTable,
			Columns: []string{netinterface.OnPoInterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: portchannelinterface.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if niuo.mutation.ModeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.ModeTable,
			Columns: []string{netinterface.ModeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: netinterfacemode.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := niuo.mutation.ModeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.ModeTable,
			Columns: []string{netinterface.ModeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: netinterfacemode.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if niuo.mutation.HaveVlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   netinterface.HaveVlansTable,
			Columns: netinterface.HaveVlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vlan.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := niuo.mutation.RemovedHaveVlansIDs(); len(nodes) > 0 && !niuo.mutation.HaveVlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   netinterface.HaveVlansTable,
			Columns: netinterface.HaveVlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vlan.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := niuo.mutation.HaveVlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   netinterface.HaveVlansTable,
			Columns: netinterface.HaveVlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vlan.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if niuo.mutation.NativeOnVlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.NativeOnVlanTable,
			Columns: []string{netinterface.NativeOnVlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vlan.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := niuo.mutation.NativeOnVlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netinterface.NativeOnVlanTable,
			Columns: []string{netinterface.NativeOnVlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vlan.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NetInterface{config: niuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, niuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{netinterface.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
