// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mrzack99s/netcoco/ent/netinterfacemode"
	"github.com/mrzack99s/netcoco/ent/predicate"
)

// NetInterfaceModeDelete is the builder for deleting a NetInterfaceMode entity.
type NetInterfaceModeDelete struct {
	config
	hooks    []Hook
	mutation *NetInterfaceModeMutation
}

// Where adds a new predicate to the NetInterfaceModeDelete builder.
func (nimd *NetInterfaceModeDelete) Where(ps ...predicate.NetInterfaceMode) *NetInterfaceModeDelete {
	nimd.mutation.predicates = append(nimd.mutation.predicates, ps...)
	return nimd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (nimd *NetInterfaceModeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(nimd.hooks) == 0 {
		affected, err = nimd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NetInterfaceModeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nimd.mutation = mutation
			affected, err = nimd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(nimd.hooks) - 1; i >= 0; i-- {
			mut = nimd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nimd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (nimd *NetInterfaceModeDelete) ExecX(ctx context.Context) int {
	n, err := nimd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (nimd *NetInterfaceModeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: netinterfacemode.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: netinterfacemode.FieldID,
			},
		},
	}
	if ps := nimd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, nimd.driver, _spec)
}

// NetInterfaceModeDeleteOne is the builder for deleting a single NetInterfaceMode entity.
type NetInterfaceModeDeleteOne struct {
	nimd *NetInterfaceModeDelete
}

// Exec executes the deletion query.
func (nimdo *NetInterfaceModeDeleteOne) Exec(ctx context.Context) error {
	n, err := nimdo.nimd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{netinterfacemode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (nimdo *NetInterfaceModeDeleteOne) ExecX(ctx context.Context) {
	nimdo.nimd.ExecX(ctx)
}
