// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mrzack99s/netcoco/ent/portchannelinterface"
	"github.com/mrzack99s/netcoco/ent/predicate"
)

// PortChannelInterfaceDelete is the builder for deleting a PortChannelInterface entity.
type PortChannelInterfaceDelete struct {
	config
	hooks    []Hook
	mutation *PortChannelInterfaceMutation
}

// Where adds a new predicate to the PortChannelInterfaceDelete builder.
func (pcid *PortChannelInterfaceDelete) Where(ps ...predicate.PortChannelInterface) *PortChannelInterfaceDelete {
	pcid.mutation.predicates = append(pcid.mutation.predicates, ps...)
	return pcid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pcid *PortChannelInterfaceDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pcid.hooks) == 0 {
		affected, err = pcid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PortChannelInterfaceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pcid.mutation = mutation
			affected, err = pcid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pcid.hooks) - 1; i >= 0; i-- {
			mut = pcid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pcid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcid *PortChannelInterfaceDelete) ExecX(ctx context.Context) int {
	n, err := pcid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pcid *PortChannelInterfaceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: portchannelinterface.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: portchannelinterface.FieldID,
			},
		},
	}
	if ps := pcid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pcid.driver, _spec)
}

// PortChannelInterfaceDeleteOne is the builder for deleting a single PortChannelInterface entity.
type PortChannelInterfaceDeleteOne struct {
	pcid *PortChannelInterfaceDelete
}

// Exec executes the deletion query.
func (pcido *PortChannelInterfaceDeleteOne) Exec(ctx context.Context) error {
	n, err := pcido.pcid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{portchannelinterface.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pcido *PortChannelInterfaceDeleteOne) ExecX(ctx context.Context) {
	pcido.pcid.ExecX(ctx)
}
